#!/bin/bash
# fenix_bot.sh — Bot Telegram + Generador de Repos con IA
# Ver version completa en netbook-tools/fenix_bot.sh
source /etc/mcp-node/settings.env
TELEGRAM_TOKEN="8798870256:AAGn7Re3YYWFRLcT2yjuDnD2GR98OyALLB8"
ALLOWED_CHAT_ID="8046308066"
TELEGRAM_API="https://api.telegram.org/bot${TELEGRAM_TOKEN}"
WORKSPACE="/tmp/fenix_build"
LOCK_FILE="/tmp/fenix_bot.lock"
OFFSET_FILE="/tmp/fenix_offset"
LOG_FILE="/var/log/mcp-node/fenix_bot.log"
log() { echo "[$(date '+%H:%M:%S')] $1" | tee -a "$LOG_FILE"; }
telegram_send() { curl -s -X POST "${TELEGRAM_API}/sendMessage" -H "Content-Type: application/json" -d "{\"chat_id\":\"${ALLOWED_CHAT_ID}\",\"text\":\"${1}\",\"parse_mode\":\"Markdown\"}" > /dev/null; }
cleanup() { rm -f "$LOCK_FILE"; rm -rf "$WORKSPACE"; }
trap cleanup EXIT
interpretar_orden() {
    local orden="$1"
    local schema='{"type":"object","properties":{"project_name":{"type":"string"},"description":{"type":"string"},"tech_stack":{"type":"string"},"files":{"type":"array","items":{"type":"object","properties":{"filepath":{"type":"string"},"content":{"type":"string"}}}}}}'
    local prompt="Sos un generador de repositorios de código. El usuario pidió: \"${orden}\". Generá un repositorio completo y funcional. REGLAS: project_name solo letras minúsculas números y guiones sin espacios. Incluí README.md siempre. Máximo 8 archivos. Si es web: index.html + style.css + script.js. Si es API: archivos del servidor + README + requirements. Respondé SOLO con el JSON."
    curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${GEMINI_KEY_1}" -H "Content-Type: application/json" -d "{\"contents\":[{\"parts\":[{\"text\":\"${prompt}\"}]}],\"generationConfig\":{\"responseMimeType\":\"application/json\",\"responseSchema\":${schema},\"maxOutputTokens\":8192,\"temperature\":0.3}}" > /tmp/gemini_response.json 2>/dev/null
    jq -r '.candidates[0].content.parts[0].text' /tmp/gemini_response.json 2>/dev/null
}
crear_archivos() {
    local json_payload="$1"
    local project_name=$(echo "$json_payload" | jq -r '.project_name' 2>/dev/null)
    [ -z "$project_name" ] || [ "$project_name" = "null" ] && return 1
    mkdir -p "${WORKSPACE}/${project_name}" && cd "${WORKSPACE}/${project_name}" || return 1
    echo "$json_payload" | jq -c '.files[]' 2>/dev/null | while read -r file_obj; do
        local filepath=$(echo "$file_obj" | jq -r '.filepath')
        local content=$(echo "$file_obj" | jq -r '.content')
        mkdir -p "$(dirname "$filepath")"
        printf '%s' "$content" > "$filepath"
    done
    echo "$project_name"
}
crear_repo_github() {
    local project_name="$1" description="$2"
    local response=$(curl -s -X POST -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.v3+json" "https://api.github.com/user/repos" -d "{\"name\":\"${project_name}\",\"description\":\"${description}\",\"private\":false,\"auto_init\":false}")
    local repo_url=$(echo "$response" | jq -r '.html_url')
    [ -z "$repo_url" ] || [ "$repo_url" = "null" ] && echo "ERROR: $(echo "$response" | jq -r '.message')" && return 1
    cd "${WORKSPACE}/${project_name}" || return 1
    git init -b main > /dev/null 2>&1
    git config user.email "fenix@netbook.local" && git config user.name "Fenix MCP Bot"
    git add . > /dev/null 2>&1
    git commit -m "Initial commit - Generated by Fenix MCP AI Agent" > /dev/null 2>&1
    git remote add origin "https://${GITHUB_USER}:${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${project_name}.git"
    git push -u origin main > /dev/null 2>&1
    echo "$repo_url"
}
log "=== FENIX BOT INICIADO ==="
telegram_send "🤖 *Fenix Bot activo*\. Mandame qué repo querés crear\."
OFFSET=0; [ -f "$OFFSET_FILE" ] && OFFSET=$(cat "$OFFSET_FILE")
while true; do
    UPDATES=$(curl -s "${TELEGRAM_API}/getUpdates?timeout=30&offset=${OFFSET}" 2>/dev/null)
    UPDATE_COUNT=$(echo "$UPDATES" | jq '.result | length' 2>/dev/null)
    [ -z "$UPDATE_COUNT" ] || [ "$UPDATE_COUNT" = "0" ] && continue
    echo "$UPDATES" | jq -c '.result[]' 2>/dev/null | while read -r update; do
        UPDATE_ID=$(echo "$update" | jq -r '.update_id')
        CHAT_ID=$(echo "$update" | jq -r '.message.chat.id')
        TEXT=$(echo "$update" | jq -r '.message.text')
        echo "$((UPDATE_ID + 1))" > "$OFFSET_FILE"
        [ "$CHAT_ID" != "$ALLOWED_CHAT_ID" ] && continue
        [ -z "$TEXT" ] || [ "$TEXT" = "null" ] && continue
        [ "$TEXT" = "/start" ] || [ "$TEXT" = "/help" ] && telegram_send "🤖 Mandame qué querés crear\. Ej: _landing page para pizzería_" && continue
        [ "$TEXT" = "/status" ] && telegram_send "📊 RAM libre: $(free -m | awk 'NR==2{print $4}')MB" && continue
        [ -f "$LOCK_FILE" ] && telegram_send "⏳ *Sistema ocupado*\. Esperá un momento\." && continue
        touch "$LOCK_FILE"
        telegram_send "⚙️ Procesando: _${TEXT}_\.\.\."
        JSON_RESULT=$(interpretar_orden "$TEXT")
        [ -z "$JSON_RESULT" ] || [ "$JSON_RESULT" = "null" ] && telegram_send "❌ Error interpretando orden\." && rm -f "$LOCK_FILE" && continue
        PROJECT_NAME=$(echo "$JSON_RESULT" | jq -r '.project_name')
        DESCRIPTION=$(echo "$JSON_RESULT" | jq -r '.description')
        FILE_COUNT=$(echo "$JSON_RESULT" | jq '.files | length')
        telegram_send "✅ Código generado\: \`${PROJECT_NAME}\` \(${FILE_COUNT} archivos\)\. Subiendo\.\.\."
        mkdir -p "$WORKSPACE"
        crear_archivos "$JSON_RESULT"
        REPO_URL=$(crear_repo_github "$PROJECT_NAME" "$DESCRIPTION")
        if echo "$REPO_URL" | grep -q "ERROR"; then
            telegram_send "❌ Error: ${REPO_URL}"
        else
            telegram_send "🎉 *Repo listo\!*
📁 \`${PROJECT_NAME}\`
🔗 ${REPO_URL}
_${FILE_COUNT} archivos generados por Fenix AI_"
        fi
        rm -f "$LOCK_FILE"
        rm -rf "${WORKSPACE}/${PROJECT_NAME}"
    done
done
